apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPCEndpoint
metadata:
  name: ssm-vpce
  labels:
    name: ssm-vpce
spec:
  forProvider:
    region: eu-west-3
    privateDNSEnabled: true
    vpcEndpointType: Interface
    serviceName: com.amazonaws.eu-west-3.ssm
    securityGroupIdSelector:
      matchLabels:
        group: compute-sg
    subnetIdSelector:
      matchLabels:
        type: private
    vpcIdSelector:
      matchLabels:
        name: sandbox-vpc
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPCEndpoint
metadata:
  name: ssmmessages-vpce
  labels:
    name: ssmmessages-vpce
spec:
  forProvider:
    region: eu-west-3
    privateDNSEnabled: true
    vpcEndpointType: Interface
    serviceName: com.amazonaws.eu-west-3.ssmmessages
    securityGroupIdSelector:
      matchLabels:
        group: compute-sg
    subnetIdSelector:
      matchLabels:
        type: private
    vpcIdSelector:
      matchLabels:
        name: sandbox-vpc
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPCEndpoint
metadata:
  name: ec2messages-vpce
  labels:
    name: ec2messages-vpce
spec:
  forProvider:
    region: eu-west-3
    privateDNSEnabled: true
    vpcEndpointType: Interface
    serviceName: com.amazonaws.eu-west-3.ec2messages
    securityGroupIdSelector:
      matchLabels:
        group: compute-sg
    subnetIdSelector:
      matchLabels:
        type: private
    vpcIdSelector:
      matchLabels:
        name: sandbox-vpc
  providerConfigRef:
    name: aws
