apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: sandbox-vpc
  labels:
    name: sandbox-vpc
spec:
  forProvider:
    region: eu-west-3
    cidrBlock: 10.10.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
      - key: Name
        value: sandbox-vpc
    instanceTenancy: default
  providerConfigRef:
    name: aws
