apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = <crossplane_user_access_key>
    aws_secret_access_key = <crossplane_user_secret_key>
